### ISSUE TITLE
Support for React Nodes in previousLabel/nextLabel for Custom Pagination Labels

### ISSUE THREAD

**Issue by NereonNeo** [jonelantha/react-responsive-pagination#110]
Hi team,

I recently came across your amazing pagination library, and I must say, it looks very promising. I've worked with other libraries before, but yours stood out to me, especially for its adaptability. I needed to create a responsive pagination system, and I thought your library would fit perfectly for my project.

However, I encountered a significant limitation: passing a React node to previousLabel/nextLabel is still in the alpha stage. This was quite a setback for me since my project requires custom labels. As a result, I had to put your library on hold and implement my own solution for the time being.

I wanted to know when you plan to fully support this feature, as it would greatly improve the flexibility of the library. I see a lot of potential in what you're building, and this addition could really push it forward!

Thank you for your hard work and the great tools you're creating!

P.S. Sincerely, a happy user 😊

**Comment by jonelantha** [comment]
Hi, many thanks for your positive feedback 😄 

The reason why the support is considered experimental is due to a known edge case where if you change the label prop to a different react component, the Pagination component may not react to the change correctly. It will display the new label fine, but if the new label is much larger or smaller than the previous one, then the wrong number of pages may be displayed.

The good news is that #104 once merged will help with the above issue

So if react elements are working fine for you then please consider them supported, there are no plans to remove the support which currently exists and the experimental status should be removed soon.

If instead you're seeing a different issue to the one mentioned above, please provide more details, thanks 😄

**Comment by NereonNeo** [comment]
@jonelantha I am very glad to hear this 😄, I will follow the updates. Good luck to you guys!
